---
title: "Project 1"
author: "Sabrina Harris"
date: "2024-03-28"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(ggpubr)
library(forcats)
library(viridis)

sales_data <- read.csv('car_prices.csv')
```

```{r}
set.seed(559)

sample_sales_data <- sample_n(sales_data,300)
```


```{r}
sample_sales_data <- sample_sales_data %>%
  mutate(saledate = sub(" GMT.*$", "", saledate),
         saledate = mdy_hms(saledate), 
         saledate = as.Date(saledate))

sample_sales_data$saledate = as.Date(sample_sales_data$saledate)
```


```{r}
ggplot(data = sample_sales_data, aes(x = sellingprice, y = odometer))+
  geom_point(color = viridis(10)[6], alpha = 0.6)+
  labs(x = "Sale Price",
       y = "Odometer reading (miles)",
       title = 'Sale Price vs Odometer Reading',
       subtitle = 'Based on Kaggle Vehicle Sales Dataset 2014-2015')+
  scale_x_continuous(expand = c(0,0),
                     limits = c(-1000,85000),
                     breaks = c(0,10000,20000,30000,40000,50000,60000,70000,80000),
                     labels = c('$0','$10,000','$20,000','$30,000','$40,000','$50,000','$60,000','$70,000','$80,000'))+
  scale_y_continuous(expand = c(0,0),
                     limits = c(-10000,320000),
                     breaks = c(0,50000,100000,150000,200000,250000,300000),
                     labels = c('0','50k','100k','150k','200k','250k','300k')
  )+
  theme_bw()+
  theme(axis.text.x = element_text(face = 'bold',size = 10 ),
        axis.text.y = element_text(face = 'bold',size = 10))+
  guides(fill = 'none')
#ggsave('scatterplot.png')
```

```{r}

sample_sales_data <- sample_sales_data %>%
  mutate(vehicle_age = year(saledate) - year)
#create a column to find the age of the car at the time it was sold
```

```{r}
sample_sales_data <- sample_sales_data %>%
  mutate(vehicle_age = ifelse(vehicle_age < 0, 0, vehicle_age))
#remove negative numbers from column
```

```{r}
ggplot(data = sample_sales_data, aes(x = sellingprice, y = vehicle_age))+
  geom_point()
#this one will probably be better as a categorical variable

```


```{r}

sample_sales_data <- sample_sales_data %>%
  mutate(vehicle_age_cat = case_when(
    vehicle_age >= 0 & vehicle_age <= 1 ~ "0-1",
    vehicle_age >= 2 & vehicle_age <= 5 ~ "2-5",
    vehicle_age > 5 & vehicle_age <= 10 ~ "6-10",
    vehicle_age > 10 ~ "11+",
    TRUE ~ "Unknown"
  ))

```

```{r}
sample_sales_data <- sample_sales_data %>%
  mutate(body = tolower(body)) 
```


```{r}
sample_sales_data <- sample_sales_data %>%
  mutate(across(everything(), ~na_if(trimws(.), "")))
```


```{r}
ggplot(data = sample_sales_data, aes(x = color))+
  geom_bar()+
  facet_wrap(~body)
```


```{r}
unique(sample_sales_data$body)
```

```{r}
sample_sales_data <- sample_sales_data %>%
  mutate(body_recode = case_when(
    body %in% c("sedan", "coupe", "g sedan", "hatchback", "g coupe","convertible") ~ "Sedan",
    body %in% c("suv",'hatchback','minivan') ~ "SUV",
    TRUE ~ "Other"
  ))
```


```{r}
ggplot(data = sample_sales_data, aes(x = color))+
  geom_bar()+
  facet_wrap(~body_recode)
```
```{r}
sample_sales_data <- sample_sales_data %>%
  mutate(color_recode = case_when(
    color %in% c("blue", "black", "silver", "gray", "red", "white") ~ color,
    TRUE ~ "Other"
  ))
```

```{r}
ggplot(data = sample_sales_data, aes(x = color_recode))+
  geom_bar()+
  facet_wrap(~body_recode)
```


```{r}
ggplot(data = sample_sales_data, aes(x = color_recode))+
  geom_bar()+
  labs(x = 'Color',
       title = 'Color of Cars sold by Body Style',
       subtitle = 'based on Kaggle Vehicle Sales Dataset')+
  ylab(NULL)+
  facet_wrap(~body_recode)+
  theme_bw()
```


```{r}
sales_data <- sales_data %>%
  mutate(body = tolower(body)) %>%
  mutate(across(everything(), ~na_if(trimws(.), ""))) %>%
  mutate(body_recode = case_when(
    body %in% c("sedan", "coupe", "g sedan", "hatchback", "g coupe","convertible") ~ "Sedan",
    body %in% c("suv",'hatchback','minivan') ~ "SUV",
    TRUE ~ "Other"
  )) %>% 
  mutate(color_recode = case_when(
    color %in% c("blue", "black", "silver", "gray", "red", "white") ~ color,
    TRUE ~ "Other"
  ))
  
```

```{r}
ggplot(data = sales_data, aes(x = color_recode))+
  geom_bar()+
  labs(x = 'Color',
       title = 'Color of Cars sold by Body Style',
       subtitle = 'based on Kaggle Vehicle Sales Dataset')+
  ylab(NULL)+
  facet_wrap(~body_recode)+
  theme_bw()
```

```{r}
plot_data <- sales_data %>% group_by(body_recode) %>% count(color_recode) %>% mutate(Percent = 100*n/sum(n))
plot_data
```


```{r}
ggplot(data=plot_data, aes(x=color_recode, y=Percent, fill=color_recode)) +
  geom_bar(stat="identity", color="black") +
  labs(x = 'Color',
       title = 'Color of Cars sold by Body Style',
       subtitle = 'Based on Kaggle Vehicle Sales Dataset 2014-2015')+
  theme_bw()+
  guides(fill = 'none')+
  facet_wrap(~body_recode)
```
```{r}
plot_data %>%
  ggplot(aes(x = body_recode, y = Percent, fill = color_recode, group = color_recode)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.6) +
  labs(y = "Proportion", x = "Body Type", fill = "Color") +
  
  theme_minimal()
```

```{r}
sales_data$sellingprice <- as.numeric(sales_data$sellingprice)
```


```{r}

ggplot(data = sales_data, aes(x = sellingprice))+
  geom_density(color = 'black', fill = 'purple')+
  scale_x_continuous(limits = c(0,75000))+
  theme_bw()+
  theme(axis.line.y=element_blank(),
axis.text.y=element_blank(),
axis.ticks.y=element_blank(),
axis.title.y=element_blank())
```
```{r}
sample_sales_data$sellingprice <- as.numeric(sample_sales_data$sellingprice)
sample_sales_data$odometer <- as.numeric(sample_sales_data$odometer)
```

```{r}

ggscatterhist(
    sample_sales_data, x = "sellingprice", y = "odometer",
    margin.plot = "histogram",
    bins=15,
    margin.params = list(fill = "lightblue", color = "black")
    )
```



```{r}
library(forcats)


plot_data <- plot_data %>%
  mutate(color_recode = fct_relevel(color_recode, "Other", after = Inf), # Move "Other" to the end
         body_recode = fct_relevel(body_recode, "Other", after = Inf),   # Move "Other" for body_recode to the end
         color_recode = fct_infreq(color_recode) %>% fct_rev(), # Order colors by frequency, then reverse
         color_recode = as.factor(tools::toTitleCase(as.character(color_recode)))) # Capitalize color names

# Define a named vector with colors, including 'Other' as pink
colors <- setNames(c("#0000FF", "#000000", "#C0C0C0", "#808080", "#FF0000", "#FFFFFF", "#FFC0CB"), 
                   c("Blue", "Black", "Silver", "Gray", "Red", "White", "Other"))



```

```{r}

ggplot(plot_data, aes(x=color_recode, y=Percent, fill=color_recode)) +
  geom_bar(stat="identity", color="black", aes()) +
  scale_fill_manual(values = colors) + # Apply custom colors
  labs(
       y = 'Percent of Sales',
       title = 'Color of Cars sold by Body Style',
       subtitle = 'Based on Kaggle Vehicle Sales Dataset 2014-2015') +
  scale_x_discrete(expand = c(0,0),
                   limits = c('Black','Blue','Gray','Red','Silver','White','Other'))+
  scale_y_continuous(expand = c(0,0),
                     limits = c(0,32),
                     breaks = c(0,5,10,15,20,25,30),
                     labels = c('0%','5%','10%','15%','20%','25%','30%'))+
  theme_bw() +
  guides(fill = 'none') +
  theme(axis.text.x = element_text(face = 'bold',size = 7 ),
        axis.text.y = element_text(face = 'bold',size = 10),
        axis.title.x = element_blank())+
  facet_wrap(~body_recode)
#ggsave('histogram.png')
```


```{r}
library(ggridges)

mycolors <- viridis(10)[5:10]

ggplot(data = sales_data, aes(x = sellingprice, y = body_recode, fill = body_recode ))+
  geom_density_ridges(alpha = 0.6)+
  labs(
    x = 'Selling Price',
    y = 'Body Style',
    title = 'Selling Price Distribution by Body Style',
    subtitle = 'Based on Kaggle Vehicle Sales Dataset 2014-2015'
  )+
  scale_fill_manual(values = mycolors)+
  scale_x_continuous(
    expand = c(0,0),
    limits = c(0,62000),
    breaks = c(0,10000,20000,30000,40000,50000,60000),
    labels = c('$0','$10k','$20k','$30k','$40k','$50k','$60k')
  )+
  scale_y_discrete(expand = c(0,0))+
  guides(fill = 'none')+
  theme_bw()
#ggsave('density.png')
```

